apiVersion: v1
kind: Service
metadata:
  name: gists-api
  namespace: dev
spec:
  selector:
    app: gists-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # For local dev; change to ClusterIP if you prefer port-forwarding only